[tool.poetry]
name = "projekt"
version = "0.1.0"
description = ""
authors = ["Filip Juza <filip.juza.2000@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
opencv-python = "^4.7.0.72"
emd = {git = "https://gitlab.com/emd-dev/emd.git"}
scipy = "^1.10.1"
librosa = "^0.10.0.post2"
typed-argument-parser = "^1.8.0"
tqdm = "^4.65.0"
jupyter = "^1.0.0"
streamad = "^0.3.1"
kaleido = "0.2.1"
<<<<<<< HEAD
=======
tensorflow = "2.10"
tensorflow-io-gcs-filesystem = "0.31.0"
pydub = "^0.25.1"
seaborn = "^0.12.2"
tsfresh = "0.20.1"
lightgbm = "3.3.5"
>>>>>>> 8323a46 (add lightgbm classification)

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
pre-commit = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"